FROM resin/rpi-raspbian:latest 

# Allows to set-up HTTP(S) proxy using '--build-arg'
ARG http_proxy
ARG https_proxy

ENV http_proxy ${http_proxy}
ENV https_proxy ${https_proxy}

RUN echo $https_proxy
RUN echo $http_proxy

# Update and install core build tools
RUN apt-get update
RUN apt-get install -y apt-utils curl git wget unzip

# Install npm, nodejs
RUN apt-get remove nodered -y
RUN apt-get remove nodejs nodejs-legacy -y
RUN apt-get remove npm -y

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# Install node-wot
RUN mkdir -p /opt/node-wot/
WORKDIR /opt/node-wot/

COPY . /opt/node-wot/

RUN npm install
RUN npm run build

# Create mount point
VOLUME ["/opt/user/"]

# Forward port
EXPOSE 8080 8081

# Unset proxy
ENV http_proxy ""
ENV https_proxy ""

# Start Home Gateway
ENTRYPOINT ["/opt/node-wot/start-in-docker.sh"]
