FROM ubuntu:16.04

# Update and install core build tools
RUN apt-get update
RUN apt-get install -y apt-utils curl git wget unzip

# Install npm, nodejs
# RUN apt-get remove nodered -y
RUN apt-get remove nodejs nodejs-legacy -y
RUN apt-get remove npm -y

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# Install node-wot
RUN mkdir -p /opt/node-wot/
WORKDIR /opt/node-wot/

COPY . /opt/node-wot/

RUN npm install
RUN npm run build

# Create mount point for external app
VOLUME ["/opt/user/"]

# Forward port
EXPOSE 8080 8081

# Run the app startup script on container startup
# The entry point file must be executable
ENTRYPOINT ["/opt/node-wot/start-in-docker.sh"]
